# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 12:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompInv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompName', models.CharField(max_length=200)),
                ('UserName', models.CharField(max_length=200)),
                ('OpSys', models.CharField(max_length=200)),
                ('Model', models.CharField(max_length=200)),
                ('ServiseTag', models.CharField(max_length=200)),
                ('Processor', models.CharField(max_length=200)),
                ('Memory', models.CharField(max_length=200)),
                ('DateBoot', models.DateTimeField()),
                ('UpdNeed', models.CharField(max_length=200)),
                ('DateUpd', models.DateTimeField()),
                ('EsetNod', models.CharField(max_length=200)),
                ('PubDate', models.DateTimeField()),
                ('DateNow', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Test_u',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Field_1', models.CharField(max_length=200)),
                ('Field_2', models.CharField(max_length=200)),
                ('Field_3', models.CharField(max_length=200)),
                ('Date_create', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
