# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compinv',
            old_name='CompName',
            new_name='comp_name',
        ),
        migrations.RenameField(
            model_name='compinv',
            old_name='DateBoot',
            new_name='date_boot',
        ),
        migrations.RenameField(
            model_name='compinv',
            old_name='DateNow',
            new_name='date_now',
        ),
        migrations.RenameField(
            model_name='compinv',
            old_name='DateUpd',
            new_name='date_upd',
        ),
        migrations.RenameField(
            model_name='compinv',
            old_name='EsetNod',
            new_name='eset_nod',
        ),
        migrations.RenameField(
            model_name='compinv',
            old_name='Memory',
            new_name='memory',
        ),
        migrations.RenameField(
            model_name='compinv',
            old_name='Model',
            new_name='model_name',
        ),
        migrations.RenameField(
            model_name='compinv',
            old_name='OpSys',
            new_name='op_system',
        ),
        migrations.RenameField(
            model_name='compinv',
            old_name='Processor',
            new_name='processor',
        ),
        migrations.RenameField(
            model_name='compinv',
            old_name='PubDate',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='compinv',
            old_name='ServiseTag',
            new_name='service_tag',
        ),
        migrations.RenameField(
            model_name='compinv',
            old_name='UpdNeed',
            new_name='upd_need',
        ),
        migrations.RenameField(
            model_name='compinv',
            old_name='UserName',
            new_name='user_name',
        ),
    ]
