# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160922_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='compinv',
            name='comp_name_shot',
            field=models.CharField(default='  ', max_length=200),
            preserve_default=False,
        ),
    ]
