# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_compinv_comp_name_shot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compinv',
            name='eset_nod',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='compinv',
            name='upd_need',
            field=models.IntegerField(),
        ),
    ]
