# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20161030_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_name', models.CharField(max_length=200)),
                ('sys_field1', models.CharField(max_length=200)),
                ('sys_field2', models.CharField(max_length=200)),
                ('sys_field3', models.CharField(max_length=200)),
                ('sys_field4', models.CharField(max_length=200)),
                ('sys_field5', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Test_u',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
