# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20161101_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsetNod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eset_version', models.IntegerField()),
                ('eset_data', models.CharField(max_length=200)),
                ('eset_check', models.IntegerField()),
            ],
        ),
    ]
