# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_esetnod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EsetNod',
        ),
    ]
