# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_photobase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photobase',
            name='sam_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
