# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20161109_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='sys_field6',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
