# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_system_sys_field6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photobase',
            name='url_name',
            field=models.CharField(max_length=1000),
        ),
    ]
