# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_photobase'),
    ]

    operations = [
        migrations.AddField(
            model_name='photobase',
            name='mail_name',
            field=models.CharField(default='!', max_length=200),
            preserve_default=False,
        ),
    ]
