# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_photobase_mail_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compinv',
            name='comp_name_shot',
        ),
        migrations.RemoveField(
            model_name='compinv',
            name='date_now',
        ),
    ]
