# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_sort_button'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='sys_field3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='system',
            name='sys_field4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='system',
            name='sys_field5',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
