# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20161127_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='System_var',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_name', models.CharField(max_length=200)),
                ('sys_field1', models.CharField(max_length=200)),
                ('sys_field2', models.CharField(max_length=200)),
                ('sys_field3', models.CharField(blank=True, max_length=200)),
                ('sys_field4', models.CharField(blank=True, max_length=200)),
                ('sys_field5', models.CharField(blank=True, max_length=200)),
                ('sys_field6', models.IntegerField()),
            ],
        ),
    ]
