# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_system_var'),
    ]

    operations = [
        migrations.DeleteModel(
            name='System',
        ),
    ]
