# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_delete_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compinv',
            name='date_upd',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='compinv',
            name='eset_nod',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='compinv',
            name='service_tag',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='compinv',
            name='upd_need',
            field=models.IntegerField(blank=True),
        ),
    ]
