# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20161212_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compinv',
            name='date_upd',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
