# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20161221_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photobase',
            name='url_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
